### ISSUE TITLE
Send self-destruct messages from BOT

### ISSUE THREAD

**Issue by grmpyninja** [wireapp/wire-bot-java#21]
Send some info messages or responses to commands as self-destruct messages to not SPAM the main chat.

**Comment by dkovacevic** [comment]
I am not sure I get what the `self-destruct` message is.
In case you want to trigger a message from a specific bot you can:
```
curl -XPOST http://localhost:8051/tasks/broadcast --data  "bot=$BOTID&text=Hello"
```

**Comment by DivineOmega** [comment]
I assume @grmpyninja is referring to Wire's timed messages.

**Comment by dkovacevic** [comment]
I see. OK, I will `timed message` sending to WireClient class. Thanks!

**Comment by dkovacevic** [comment]
Timed messages (Txt for now) implemented in 0.3.1

**Comment by qirtaiba** [comment]
Can you explain how we use it or show us any example code?  The API documentation at https://github.com/wireapp/wire-bot-java/wiki/API-Service doesn't say anything about this feature.

**Comment by dkovacevic** [comment]
For now you can send `Timed messages` as text only.
https://github.com/wireapp/bot-sdk/blob/master/src/main/java/com/wire/bots/sdk/WireClient.java#L54

If needed I can add the same support for assets.

The code that sets the proto is here:
https://github.com/wireapp/bot-sdk/blob/master/src/main/java/com/wire/bots/sdk/assets/Text.java#L48-L56

**Comment by qirtaiba** [comment]
Just one more question. Can it be used with the node sdk as well as the Java one?  Nothing that I have seen in the links above seems to relate to the node sdk.  Thanks.

**Comment by dkovacevic** [comment]
Unfortunately we don't have ephemeral messages implemented for Node.js.
Maybe you could help us out with that?
The starting point is here:
https://github.com/wireapp/bot-sdk-node/blob/master/lib/messages.proto#L26-L41

**Comment by qirtaiba** [comment]
Not sure whether my coding skills are up to snuff but I will try.

**Comment by qirtaiba** [comment]
No, after quite a big of trying I can't figure it out. But I am willing to pay a bounty for this feature to be implemented by someone else.

**Comment by qirtaiba** [comment]
I was about to give up, but it turned out to be simpler than I thought. The sendMessage function in bot_instance.js just needs to be changed to:

> sendMessage(message, cb) {
>    const msg = {
>      message_id: uuidV1(),
>      ephemeral: {
>        expire_after_millis: 86400000,
>        text: {
>          content: message,
>          mention: [],
>          link_preview: [],
>        },
>      },
>    };
>    this.service.sendMessage(this.botID, msg, cb);
>  }

This is for hard-coding the disappearing time as 1 day, but I can work on a pull request that would make it configurable.
