### ISSUE TITLE
Request for the ability to make/respond to connection requests

### ISSUE THREAD

**Issue by Cnly** [wireapp/wire-bot-java#25]
I noticed that the current version of API doesn't provide a method for bots to make/respond to connection requests with users? Hope this can be added soon:)

**Comment by dkovacevic** [comment]
Bot will never be able to send connect requests. We don't want them to be able to spam people :). Only **Users** (humans) are able to initiate conversation with a bot. 
There is no need for a bot ( Service) to accept any connect request as people adding particular service into a conversation automatically enables this Service.

**Comment by Cnly** [comment]
But then users will only be able to add bots back through the invite link after deleting the conversation... which is not supported by the mobile app now...
Plus, are the messages sent by users to a bot vanished, if the bot gets offline for a while?

**Comment by dkovacevic** [comment]
Yes. We are working on adding search for the Bots. When that's been implemented users will be able to search for the bot (by name, tags,...) and add it into any conv they are currently in.

If Bot receives a message while temporarily unavailable the message is lost :(. It's up to Bot Provider (you) to handle downtimes.

**Comment by Cnly** [comment]
Cool. Then maybe you'll need to remove the CONNECT button from a bot's profile in the app.
