### ISSUE TITLE
change full or user name of my contacts

### ISSUE THREAD

**Issue by orcas-mgleich** [wireapp/wire-bot-java#26]
How can I change the displayed name of my contacts. If I have over 200 contacts I don't know how is "AP" or "blind23". Better would be a possibility where I can change the displayed name of my contacts for my view only.

**Comment by DivineOmega** [comment]
I believe you meant to add this to the iOS and/or Android app issues.

iOS: https://github.com/wireapp/wire-ios/issues
Android: https://github.com/wireapp/wire-android/issues

**Comment by orcas-mgleich** [comment]
With pleasure. But does it works in the web client?

**Comment by DivineOmega** [comment]
Uncertain. If you need to add the issue for the web client, you can do so here:

https://github.com/wireapp/wire-webapp/issues

**Comment by orcas-mgleich** [comment]
Thanks, now I have found corresponding tasks.

- https://github.com/wireapp/wire-ios/issues/208
- https://github.com/wireapp/wire-android/issues/248
  - https://github.com/wireapp/wire-android/issues/214
  - https://github.com/wireapp/wire-android/issues/310
  - https://github.com/wireapp/wire-android/issues/451

Functionality is in process and I am waiting.
Thanks, this issue can be closed.

**Comment by 3raserHead** [comment]
+1 
This is really important to implement, not knowing who are the contacts defeat the purpose of having a contact list...
