### ISSUE TITLE
Screen share fails for subsequent users

### ISSUE THREAD

**Issue by StevenMapes** [wireapp/wire-bot-java#27]
During a call the initial screen share works fine but if that share is that stopped and another person tried to then share their screen it either completely fails, without raising an error, or just shares a black screen.

Tested in both browser and desktop clients
 Windows -> Windows, Windows -> Linux, Linux <- Windows

Version 2.11.2685 (Linux)
Version 2.11.2712 (Windows)

**Comment by david-wire** [comment]
Hello, I am assuming this was intended for: https://github.com/wireapp/wire-desktop?
Could you please create the issue you reported in that repository? Thanks.
