### ISSUE TITLE
Not able to login without email address

### ISSUE THREAD

**Issue by CordlessWool** [wireapp/wire-bot-java#28]
Hello,

a friend of me is not able to login anymore. She only wants to login with her phone number and not with her email address. But after she login the app request an email address. Do you changed it or is it a bug? She has an Android phone and used wire since today.

**Comment by DivineOmega** [comment]
Hi there,

Can I suggest you re-post this in the Wire for Android issues section here: https://github.com/wireapp/wire-android/issues ?

It's likely to get more attention there. You've accidentally posted in the area designed for creating Wire bots.

Many thanks.

**Comment by CordlessWool** [comment]
oh ok, sorry i did not saw that it was the bot.
