### ISSUE TITLE
JavaDoc (and/or source?) for com.wire.wbotz

### ISSUE THREAD

**Issue by NfNitLoop** [wireapp/wire-bot-java#3]
Having the sample hello app is a nice start, but there are a lot of things you can't tell from the sample code.  It would be nice to have JavaDoc documentation for the Java API. Or the source code, so that we can just read the source to answer questions four ourselves. :)

**Comment by dkovacevic** [comment]
JavaDoc and source are available [here](https://github.com/wireapp/bot-sdk)
